name: mi_card
description: A contact flutter application.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Open Sans
    fonts:
    - asset: 'fonts/OpenSans-Light.ttf'

  - family:  Source Sans Pro
    fonts:
    - asset: 'fonts/SourceSansPro-Regular.ttf'